///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest120
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest120Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("18a2ab0f-278d-42c6-85b0-6abd91cb7d1d")]
    public partial class MyTest120Repository : RepoGenBaseFolder
    {
        static MyTest120Repository instance = new MyTest120Repository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTest120Repository element repository.
        /// </summary>
        [RepositoryFolder("18a2ab0f-278d-42c6-85b0-6abd91cb7d1d")]
        public static MyTest120Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest120Repository() 
            : base("MyTest120Repository", "/", null, 0, false, "18a2ab0f-278d-42c6-85b0-6abd91cb7d1d", ".\\RepositoryImages\\MyTest120Repository18a2ab0f.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("18a2ab0f-278d-42c6-85b0-6abd91cb7d1d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest120RepositoryFolders
    {
    }
#pragma warning restore 0436
}
